# -*- coding: utf-8 -*-
"""Tugas Sistem Pakar (Forward Chaining, & Backward Chaining).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TpK8a9LIQRFFbFfk1febJ_dUKbpKQqDB
"""

!pip install frozendict==2.3.4
!pip install experta --no-deps
from experta import *

class Diagnosis(KnowledgeEngine):

    @Rule(Fact(demam=True) & Fact(sakit_kepala=True) & Fact(nyeri_otot=True))
    def malaria(self):
        print("Diagnosis: Kamu mungkin terkena Malaria.")

    @Rule(Fact(mual=True) & Fact(muntah=True) & Fact(sakit_perut=True))
    def keracunan_makanan(self):
        print("Diagnosis: Kamu mungkin mengalami Keracunan Makanan.")

    @Rule(Fact(nyeri_dada=True) & Fact(sesak_napas=True))
    def serangan_jantung_ringan(self):
        print("Diagnosis: Kamu mungkin mengalami Serangan Jantung Ringan.")

    @Rule(Fact(pusing=True) & Fact(penglihatan_kabur=True))
    def tekanan_darah_rendah(self):
        print("Diagnosis: Kamu mungkin mengalami Tekanan Darah Rendah.")

    @Rule(Fact(gatal_kulit=True) & Fact(kemerahan_kulit=True))
    def dermatitis(self):
        print("Diagnosis: Kamu mungkin mengalami Dermatitis (iritasi kulit).")

    @Rule(
        Fact(demam=False), Fact(sakit_kepala=False), Fact(nyeri_otot=False),
        Fact(mual=False), Fact(muntah=False), Fact(sakit_perut=False),
        Fact(nyeri_dada=False), Fact(sesak_napas=False),
        Fact(pusing=False), Fact(penglihatan_kabur=False),
        Fact(gatal_kulit=False), Fact(kemerahan_kulit=False)
    )
    def sehat(self):
        print("Diagnosis: Kondisi kamu tampaknya sehat.")

def input_gejala():
    def tanya(pertanyaan):
        return input(pertanyaan + " (ya/tidak): ").strip().lower() == "ya"

    return {
        "demam": tanya("Apakah kamu demam?"),
        "sakit_kepala": tanya("Apakah kamu sakit kepala?"),
        "nyeri_otot": tanya("Apakah kamu nyeri otot?"),
        "mual": tanya("Apakah kamu merasa mual?"),
        "muntah": tanya("Apakah kamu muntah?"),
        "sakit_perut": tanya("Apakah kamu sakit perut?"),
        "nyeri_dada": tanya("Apakah kamu nyeri dada?"),
        "sesak_napas": tanya("Apakah kamu sesak napas?"),
        "pusing": tanya("Apakah kamu merasa pusing?"),
        "penglihatan_kabur": tanya("Apakah penglihatanmu kabur?"),
        "gatal_kulit": tanya("Apakah kulitmu terasa gatal?"),
        "kemerahan_kulit": tanya("Apakah ada kemerahan pada kulitmu?")
    }

if __name__ == "__main__":
    print("=== Sistem Pakar Diagnosa Penyakit (Versi Ringkas) ===")
    print("Silakan jawab pertanyaan berikut dengan 'ya' atau 'tidak':")
    gejala = input_gejala()

    engine = Diagnosis()
    engine.reset()

    for nama, nilai in gejala.items():
        engine.declare(Fact(**{nama: nilai}))

    engine.run()
